CREATE TYPE public.app_role AS ENUM ('admin','clinician');
CREATE TABLE public.user_roles (user_id uuid NOT NULL, role public.app_role NOT NULL, PRIMARY KEY(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
CREATE POLICY "read own role" ON public.user_roles FOR SELECT TO authenticated USING (user_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE TABLE public.clinician_profiles (user_id uuid PRIMARY KEY, name text NOT NULL DEFAULT '', specialty text NOT NULL DEFAULT '', language text NOT NULL DEFAULT 'bg', ai_instructions text NOT NULL DEFAULT '', recording_preferences jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.clinician_profiles TO authenticated; GRANT ALL ON public.clinician_profiles TO service_role;
ALTER TABLE public.clinician_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own profile" ON public.clinician_profiles FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE TABLE public.consultations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinician_id uuid NOT NULL, patient_name text NOT NULL DEFAULT '', patient_identifier text NOT NULL DEFAULT '', patient_age integer, patient_sex text, mode text NOT NULL CHECK (mode IN ('conversation','dictation')), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','recording','complete')), consent_at timestamptz, consent_notice_version text, duration_seconds integer NOT NULL DEFAULT 0, patient_instructions text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.consultations TO authenticated; GRANT ALL ON public.consultations TO service_role;
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own consultations" ON public.consultations FOR ALL TO authenticated USING (clinician_id=auth.uid()) WITH CHECK (clinician_id=auth.uid());
CREATE TABLE public.transcript_segments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE, clinician_id uuid NOT NULL, speaker text NOT NULL CHECK (speaker IN ('doctor','patient')), text text NOT NULL, seconds integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.transcript_segments TO authenticated; GRANT ALL ON public.transcript_segments TO service_role;
ALTER TABLE public.transcript_segments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own segments" ON public.transcript_segments FOR ALL TO authenticated USING (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid())) WITH CHECK (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid()));
CREATE TABLE public.report_sections (consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE, clinician_id uuid NOT NULL, section text NOT NULL CHECK (section IN ('anamneza','status','izsledvania','terapia')), content text NOT NULL DEFAULT '', verified_at timestamptz, PRIMARY KEY(consultation_id,section));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.report_sections TO authenticated; GRANT ALL ON public.report_sections TO service_role;
ALTER TABLE public.report_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own sections" ON public.report_sections FOR ALL TO authenticated USING (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid())) WITH CHECK (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid()));
CREATE TABLE public.session_chat_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE, clinician_id uuid NOT NULL, role text NOT NULL CHECK (role IN ('user','assistant')), content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.session_chat_messages TO authenticated; GRANT ALL ON public.session_chat_messages TO service_role;
ALTER TABLE public.session_chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own chat" ON public.session_chat_messages FOR ALL TO authenticated USING (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid())) WITH CHECK (clinician_id=auth.uid() AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id=consultation_id AND c.clinician_id=auth.uid()));
CREATE TABLE public.user_phrases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinician_id uuid NOT NULL, source text NOT NULL, replacement text NOT NULL);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.user_phrases TO authenticated; GRANT ALL ON public.user_phrases TO service_role;
ALTER TABLE public.user_phrases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own phrases" ON public.user_phrases FOR ALL TO authenticated USING (clinician_id=auth.uid()) WITH CHECK (clinician_id=auth.uid());
CREATE TABLE public.specialty_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), specialty text NOT NULL UNIQUE, instructions text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.specialty_templates TO authenticated; GRANT INSERT,UPDATE,DELETE ON public.specialty_templates TO authenticated; GRANT ALL ON public.specialty_templates TO service_role;
ALTER TABLE public.specialty_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read templates" ON public.specialty_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin manage templates" ON public.specialty_templates FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.service_settings (key text PRIMARY KEY, value text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.service_settings TO authenticated; GRANT ALL ON public.service_settings TO service_role;
ALTER TABLE public.service_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin settings" ON public.service_settings FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "own audio objects read" ON storage.objects FOR SELECT TO authenticated USING (bucket_id='consultation-audio' AND (storage.foldername(name))[1]=auth.uid()::text AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id::text=(storage.foldername(name))[2] AND c.clinician_id=auth.uid()));
CREATE POLICY "own audio objects insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id='consultation-audio' AND (storage.foldername(name))[1]=auth.uid()::text AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id::text=(storage.foldername(name))[2] AND c.clinician_id=auth.uid()));
CREATE POLICY "own audio objects delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id='consultation-audio' AND (storage.foldername(name))[1]=auth.uid()::text AND EXISTS(SELECT 1 FROM public.consultations c WHERE c.id::text=(storage.foldername(name))[2] AND c.clinician_id=auth.uid()));
